apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-v1.1
spec:
  replicas: 12
  selector:
    matchLabels:
      app: rts-service
  template:
    metadata:
      labels:
        app: rts-service
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: zone # evenly distribution wrt zones
        whenUnsatisfiable: DoNotSchedule
      - maxSkew: 1
        topologyKey: node # evenly distribution wrt nodes 
        whenUnsatisfiable: DoNotSchedule
      containers:
      - name: nginx-container
        image: nginx:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
