apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1  # name of deployment
spec:
  replicas: 12
  selector:
    matchLabels:
      app: nginx  # pod label
  template:
    metadata:
      labels:
        app: nginx  # pod label
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: node
        whenUnsatisfiable: DoNotSchedule

      containers:
      - name: nginx-container
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80


