apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1  # deployment-name
spec:
  replicas: 5
  selector:
    matchLabels:
      app: billing-service  # pod-name
  template:
    metadata:
      labels:
        app: billing-service  # pod-name
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      tolerations:   
      - key: "gpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
